### ISSUE TITLE
Cannot run nami with `--log-level trace`: 

### ISSUE THREAD

**Issue by akvadrako** [bitnami/nami#42]
I am trying to debug a nami package, but if I try to adjust the logging level it bails:
```
$ docker run -it docker.io/bitnami/discourse:2.5.0 nami --log-level trace start --foreground discourse

Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    ERROR com.bitnami.discourse is not fully installed. You cannot execute commands
nami    TRACE Error: com.bitnami.discourse is not fully installed. You cannot execute commands
    at NamiCliApp._ensureComponentIsInitialized (/opt/bitnami/nami/cli/nami-app.js:185:13)
    at Command.callback (/opt/bitnami/nami/cli/nami-app.js:559:16)
    at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:527:30)
    at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:750:14)
    at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
    at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
    at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

However the same command works if I remove the log-level option:

```
$ docker run -it docker.io/bitnami/discourse:2.5.0 nami start --foreground discourse

Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
...
```

**Comment by marcosbc** [comment]
Hi all, it has been some time since we removed Nami usage from Bitnami container images, so I'll close this issue as it is not applicable anymore.
